# Generated by Django 5.1.6 on 2025-03-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentResponse', '0001_initial'),
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questions.question'),
        ),
    ]
