# Generated by Django 5.1.6 on 2025-03-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentResponse', '0002_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='student.student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentresponse',
            unique_together={('student', 'question')},
        ),
    ]
