# Generated by Django 5.1.6 on 2025-03-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_theme_question_theme'),
        ('theme', '0002_subtheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtheme',
            name='questions',
            field=models.ManyToManyField(related_name='subthemes', to='questions.question'),
        ),
        migrations.AddField(
            model_name='theme',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='themes', to='questions.question'),
        ),
    ]
