# Generated by Django 5.1.6 on 2025-03-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_theme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtheme',
            name='slug',
            field=models.SlugField(default='tipo'),
            preserve_default=False,
        ),
    ]
