# Generated by Django 5.1.6 on 2025-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_slug'),
        ('theme', '0005_subtheme_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='questions',
            field=models.ManyToManyField(related_name='themes', to='questions.question'),
        ),
    ]
