# Generated by Django 5.1.6 on 2025-03-18 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('theme', '0002_subtheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Theme',
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theme_questions', to='theme.theme'),
            preserve_default=False,
        ),
    ]
