# Generated by Django 5.1.6 on 2025-03-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_questions', to='theme.theme'),
        ),
    ]
