# Generated by Django 5.1.6 on 2025-03-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
