# Generated by Django 5.1.6 on 2025-03-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_theme_question_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='nome'),
            preserve_default=False,
        ),
    ]
